/** @type {import('tailwindcss/defaultConfig').corePlugins} */
module.exports = [
  'preflight',
  'accessibility',
  'fontWeight',
  'fontFamily',
  'fontSize',
  'fontSmoothing',
  'fontSize',
  'textAlign',
  'flex',
  'flexDirection',
  'alignItems',
  'justifyContent',
  'minHeight',
  'padding',
  'margin',
  'animation',
  'height',
  'width',
  'display',
  'userSelect',
  'textColor',
  'columns',
  'container',
  'letterSpacing',
];
