name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          npm pkg delete scripts.prepare
          npm ci

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
            envkey_NEXT_PUBLIC_GA_TRACKING_ID: "${{ secrets.NEXT_PUBLIC_GA_TRACKING_ID }}"
            envkey_NEXT_PUBLIC_FORMSPREE_ID: "${{ secrets.NEXT_PUBLIC_FORMSPREE_ID }}"
            envkey_NEXT_PUBLIC_HOTJAR_ID: ${{ secrets.NEXT_PUBLIC_HOTJAR_ID }}
            envkey_NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION: ${{ secrets.NEXT_PUBLIC_HOTJAR_SNIPPET_VERSION }}
            directory: '.'
            file_name: .env.local
            fail_on_empty: false

      - name: Lint
        run: |
          ls
          cat .env.local
          npm run lint
          npm run lint:editorconfig

      - name: Build
        run: npm run build

      - name: e2e
        uses: cypress-io/github-action@v5
        with:
          start: npm run start
          record: false
