name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      branch: ${{ github.event.head_commit.message }}
      public_path: https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}
    secrets: inherit

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Download build results
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./out
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
          TARGET_FOLDER: .
          GIT_CONFIG_NAME: ${{ github.actor }}
          GIT_CONFIG_EMAIL: ${{ github.actor }}@users.noreply.github.com
          COMMIT_MESSAGE: Deploy from commit ${{ github.sha }}

