name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
      FORMSPREE_ID: ${{ secrets.FORMSPREE_ID }}
      HOTJAR_ID: ${{ secrets.HOTJAR_ID }}
      HOTJAR_SNIPPET_VERSION: ${{ secrets.HOTJAR_SNIPPET_VERSION }}
      BASE_PATH: ''
      ORIGIN: https://salsaviva.am
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node_version: 18
      - name: Build
        uses: ./.github/actions/build
      - name: Deploy
        uses: ./.github/actions/deploy
